# Generated by Django 5.2.15 on 2026-06-29 08:37

import apps.projects.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_add_user_api_key"),
        ("core", "0001_add_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("plan", "Shot Plan (LLM)"),
                            ("image", "Image Generation"),
                            ("video", "Video Animation"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("model_id", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=150)),
                ("is_free", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="llm_models",
                        to="core.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["-is_default", "-is_free", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNING", "Planning"),
                            ("REVIEW", "Review"),
                            ("GENERATING", "Generating"),
                            ("DONE", "Done"),
                            ("VIDEO_GENERATING", "Video Generating"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("shot_plan", models.JSONField(blank=True, null=True)),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cinematic", "Cinematic"),
                            ("anime", "Anime"),
                            ("watercolor", "Watercolor"),
                            ("documentary", "Documentary"),
                            ("storybook", "Storybook"),
                            ("noir", "Noir"),
                            ("retro-pixel", "Retro Pixel"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("animate", models.BooleanField(default=False)),
                (
                    "narrator_voice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en-US-AndrewNeural", "Andrew (US Male)"),
                            ("en-US-RyanNeural", "Ryan (GB Male)"),
                            ("en-US-AvaNeural", "Ava (US Female)"),
                        ],
                        default="en-US-AndrewNeural",
                        max_length=100,
                    ),
                ),
                (
                    "music",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calm", "Calm"),
                            ("upbeat", "Upbeat"),
                            ("dramatic", "Dramatic"),
                            ("mysterious", "Mysterious"),
                            ("inspiring", "Inspiring"),
                        ],
                        default="calm",
                        max_length=200,
                    ),
                ),
                (
                    "final_video_path",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=apps.projects.models.video_upload_path,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("stale", models.BooleanField(default=False)),
                (
                    "image_model",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"capability": "image", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_projects",
                        to="projects.llmmodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "plan_model",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"capability": "plan", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_projects",
                        to="projects.llmmodel",
                    ),
                ),
                (
                    "video_model",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"capability": "video", "is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_projects",
                        to="projects.llmmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("images", "Images"),
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("assemble", "Assemble"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warn"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.IntegerField()),
                ("narration", models.TextField()),
                ("media_prompt", models.TextField()),
                (
                    "on_screen_text",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "negative_prompt",
                    models.TextField(blank=True, default="", max_length=256),
                ),
                ("animate", models.BooleanField(default=False)),
                (
                    "media_path",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=apps.projects.models.scene_media_upload_path,
                    ),
                ),
                (
                    "media_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "media_provider",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                fields=("provider", "capability", "model_id"),
                name="unique_provider_capability_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.UniqueConstraint(
                fields=("project", "index"), name="unique_scene_project_index"
            ),
        ),
    ]
