# Generated by Django 5.2.15 on 2026-06-17 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_timestamps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scene",
            old_name="image_path",
            new_name="media_path",
        ),
        migrations.AddField(
            model_name="scene",
            name="animate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scene",
            name="media_prompt",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scene",
            name="narration",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scene",
            name="negative_prompt",
            field=models.TextField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="scene",
            name="on_screen_text",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="stage",
            field=models.CharField(
                choices=[
                    ("plan", "Plan"),
                    ("images", "Images"),
                    ("voice", "Voice"),
                    ("video", "Video"),
                    ("assemble", "Assemble"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="music",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calm", "Calm"),
                    ("upbeat", "Upbeat"),
                    ("dramatic", "Dramatic"),
                    ("mysterious", "Mysterious"),
                    ("inspiring", "Inspiring"),
                ],
                default="calm",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="narrator_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-US-AndrewNeural", "Andrew (US Male)"),
                    ("en-US-RyanNeural", "Ryan (GB Male)"),
                    ("en-US-AvaNeural", "Ava (US Female)"),
                ],
                default="en-US-AndrewNeural",
                max_length=100,
            ),
        ),
    ]
