# Generated by Django 5.2.15 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_add_scene_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="narrator_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-US-AndrewNeural", "Andrew (US Male)"),
                    ("en-US-RyanNeural", "Ryan (US Male)"),
                    ("en-US-AvaNeural", "Ava (US Female)"),
                ],
                default="en-US-AndrewNeural",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLANNING", "Planning"),
                    ("REVIEW", "Review"),
                    ("IMAGE_REVIEW", "Image Review"),
                    ("GENERATING", "Generating"),
                    ("DONE", "Done"),
                    ("VIDEO_GENERATING", "Video Generating"),
                    ("FAILED", "Failed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
