# Generated by Django 5.2.15 on 2026-06-18 08:30

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_image_path_scene_media_path_scene_animate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="media_path",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.projects.models.scene_media_upload_path,
            ),
        ),
    ]
