# Generated by Django 5.2.15 on 2026-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_scene_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='narrator_voice',
            field=models.CharField(blank=True, choices=[('en-US-AndrewNeural', 'Andrew (US Male)'), ('en-US-RyanNeural', 'Ryan (US Male)'), ('en-US-AvaNeural', 'Ava (US Female)')], default='en-US-AndrewNeural', max_length=100),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['project', 'id'], name='joblog_project_id_idx'),
        ),
    ]
