# Generated by Django 5.2.15 on 2026-06-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_provider'),
        ('projects', '0003_rename_image_path_scene_media_path_scene_animate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('plan', 'Shot Plan (LLM)'), ('image', 'Image Generation'), ('video', 'Video Animation')], db_index=True, max_length=10)),
                ('model_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('is_free', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['-is_default', '-is_free', 'display_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_backend',
        ),
        migrations.AddField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, choices=[('cinematic', 'Cinematic'), ('anime', 'Anime'), ('watercolor', 'Watercolor'), ('documentary', 'Documentary'), ('storybook', 'Storybook'), ('noir', 'Noir'), ('retro-pixel', 'Retro Pixel')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('project', 'index'), name='unique_scene_project_index'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llm_models', to='core.provider'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'capability': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_projects', to='projects.llmmodel'),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'capability': 'plan', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_projects', to='projects.llmmodel'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'capability': 'video', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_projects', to='projects.llmmodel'),
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'capability', 'model_id'), name='unique_provider_capability_model'),
        ),
    ]
