# Generated by Django 5.2.15 on 2026-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_add_scene_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="preview_url",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="project",
            name="narrator_voice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-US-AndrewNeural", "Andrew (US Male)"),
                    ("en-US-RyanNeural", "Ryan (US Male)"),
                    ("en-US-AvaNeural", "Ava (US Female)"),
                ],
                default="en-US-AndrewNeural",
                max_length=100,
            ),
        ),
    ]
