# Generated by Django 5.2.15 on 2026-06-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_image_review_status"),
        ("projects", "0004_add_scene_preview_url"),
    ]

    operations = []
