# Generated by Django 5.2.15 on 2026-07-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_user_api_key"),
        ("core", "0001_add_provider"),
        ("projects", "0007_llmmodel_owner"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="llmmodel",
            name="unique_provider_capability_model_owner",
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("provider", "capability", "model_id"),
                name="unique_global_provider_capability_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("provider", "capability", "model_id", "owner"),
                name="unique_owned_provider_capability_model",
            ),
        ),
    ]
