# Generated by Django 5.2.15 on 2026-07-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_user_api_key"),
        ("projects", "0008_llmmodel_owner_partial_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_llm_models",
                to="accounts.userprofile",
            ),
        ),
    ]
