# Generated by Django 5.2.15 on 2026-07-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_llmmodel_owner_partial_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='compose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='media_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
