"""Stage 1: topic -> refined script -> shot plan JSON (one LLM call).

Pick the backend with the LLM_PROVIDER flag (a friendly name, not a model id):
"openai" -> OpenAI (OPENAI_API_KEY), "litellm"/"libra" -> the company LiteLLM
proxy (LITELLM_API_KEY, LITELLM_BASE_URL), "anthropic" -> Claude (ANTHROPIC_API_KEY),
"gemini"/"google" -> Gemini (GOOGLE_API_KEY).
With no flag set, the first configured key wins (free proxy first). Internally the
chosen model name still routes: "gpt-*" -> OpenAI, "claude-*" -> Anthropic,
"gemini-*" -> Gemini, anything else -> the LiteLLM proxy.
"""
import json
import os

from pydantic import ValidationError

from .schema import ShotPlan
from .secure import SecureString

SYSTEM = """You are a scriptwriter for a faceless YouTube channel. Given a topic or rough
script, produce a complete shot plan for a 60-90 second video built from still images,
voiceover, and captions.

Rules:
- The first scene's narration must hook the viewer in one sentence — open with a question,
  a surprising fact, or a bold claim. Never open with "Welcome" or "In this video".
- Keep narration conversational and punchy. Short sentences. No filler.
- Each scene's narration should take roughly 4-8 seconds to speak aloud.
- For educational / listicle topic videos only: end with a one-sentence call to action
  (subscribe / comment prompt). For stories, dialogues, and personal videos, do NOT add
  any call-to-action or subscribe scene — end on the story's natural final beat.
- image_prompt must describe a concrete visual, never abstract concepts. Do not ask for
  rendered text in images — text belongs in on_screen_text.
- Write each image_prompt like a cinematographer, in under ~60 words: include a shot type
  and angle (wide establishing shot, close-up, low-angle medium shot, over-the-shoulder),
  lighting (golden hour, harsh neon, soft window light, police lights raking the wall),
  and a color/mood note. Example: "low-angle medium shot, {thief} pressed against the
  lockers, red-blue police light raking across his face, shallow depth of field, tense".
- Never put negations in image_prompt ("no beard" makes models DRAW a beard) — unwanted
  traits go in the scene's negative_prompt field.
- Pick one consistent style_prefix and write every image_prompt to work with it.

CHARACTER AND VISUAL CONSISTENCY — the most important rule:

Each scene's image is generated by an AI that has NEVER seen the other scenes.
Writing "Argentina flag" in scene 3 and "Argentina flag" in scene 7 produces TWO
DIFFERENT flags from scratch. This is why people, flags, and buildings look different
every scene unless you lock them.

THE RULE: Any visual element appearing in more than one scene MUST be a character entry.
This includes: people, animals, national flags, team kits/uniforms, specific buildings,
vehicles, logos, any recurring object.

WRONG (produces a different flag every scene):
  scene 3 image_prompt: "Argentina flag waving in the wind"
  scene 7 image_prompt: "the Argentine flag above the crowd"

RIGHT (locked once, identical in every scene):
  characters: [{"name": "arg_flag", "description": "the Argentina national flag —
    three equal horizontal stripes of light sky-blue, white, and light sky-blue,
    with a bright golden Sun of May centered on the white stripe"}]
  scene 3 image_prompt: "{arg_flag} waving dramatically in the wind, low-angle shot"
  scene 7 image_prompt: "{arg_flag} flying above the roaring crowd, wide shot"

DESCRIPTION RULES:
- Description = visual identity only: colors, shape, materials, markings, clothing.
  NEVER include pose, action, emotion — those go in image_prompt.
- NEVER use size comparisons to other characters or animals (e.g. "the size of a small
  bird") — the image model will draw the compared thing. Use absolute terms only
  (e.g. "oversized", "the size of a fist", "tiny", "enormous").
- Be specific. WEAK: "an Argentina flag". STRONG: see example above.
- For objects (food, props, treasures): name the EXACT type, never generic terms.
  WEAK: "a red berry, round and glossy" (model could draw apple, pomegranate, cherry).
  STRONG: "a giant bright red strawberry with visible seeds, a green leafy top,
  and a teardrop shape". Include shape, texture, and distinguishing features.
- Always use {placeholder} — never write the description inline, never use
  "he"/"she"/"the flag"/"the man". Always {placeholder}.
- For national flags: always include stripe direction, exact colors, and central emblem.
- For people: age range, hair color/style, skin tone, every clothing item with color.

OUTFITS (when a character's clothing changes mid-story):
- If a character wears the same clothes the whole video, just put everything in
  description as usual. Do NOT use outfits for single-outfit characters.
- If a character changes clothes mid-story (gift, costume change, transformation),
  set outfits on that character: a dict mapping outfit name to a COMPLETE visual
  description (identity + clothing). The default look stays in description.
  Example:
    "description": "a 6-year-old boy with messy brown hair, round face, big hazel eyes,
     wearing a plain white t-shirt and grey shorts"
    "outfits": {"superhero": "a 6-year-old boy with messy brown hair, round face, big
     hazel eyes, wearing a red Superman t-shirt and blue jeans"}
- On each scene AFTER the change, set outfit: {"boy": "superhero"}.
  Scenes without outfit use the default description automatically.
- CRITICAL: every outfit value must repeat the full identity (face, hair, build, skin)
  from description — only change the clothing. The image model has never seen the other
  scenes, so it needs the complete look every time.

CHARACTER NEGATIVE (negative field on each character — critical for unusual traits):
- Set the character's negative field for any trait the image model tends to add wrongly.
- Bald character → negative: "hair, any hair on head, wig, hairline"
- White-haired character → negative: "dark hair, black hair, brown hair, colored hair"
- Clean-shaven character → negative: "beard, mustache, stubble, facial hair"
- This negative is automatically injected into EVERY scene the character appears in,
  so you never have to remember to add it per scene.

IS_INANIMATE FLAG:
- Set is_inanimate=true on any character that is NOT a person or animal: food, props,
  landmarks, vehicles, treasures, flags, buildings. Leave it false (default) for people
  and animals. This controls how the pipeline generates reference images (product-style
  shot vs portrait pose).

GLOBAL NEGATIVE: Always set global_negative on the plan with video-wide rules:
- Videos with people: "changing hairstyle, inconsistent clothing, different face, extra limbs, text, watermark, blurry"
- Add for flags: "wrong flag colors, altered flag design, swapped flags"
- Add for animals: "wrong species, inconsistent markings"
This is merged into EVERY scene automatically — do not repeat it per scene.

FINAL CHECK before outputting: scan every image_prompt. If any person, flag, building,
or object appears in more than one scene and is NOT referenced as {placeholder} — stop
and add it to characters. No exceptions.

Animation cost (animate field — hard limit: maximum 2 scenes per video):
- Set animate=true ONLY for the 1-2 scenes where motion is absolutely essential:
  flags waving, a character fighting/dancing/running, an animal attacking, crowd surging.
- Set animate=false for everything else: title cards, portraits, establishing shots,
  object reveals. Ken Burns zoom handles these for free.
- The pipeline enforces a hard cap of 2 — extra animate=true entries are ignored.

Motion (each still may be animated into a video clip):
- Write the motion field as a precise, physical action description — name the body
  parts, direction, and speed. Bad: "the lion attacks". Good: "the lion crouches low,
  then springs forward with front paws outstretched, mouth opening wide".
- For a speaking character: "{name} is talking, jaw moving, eyes blinking naturally,
  slight head nods as they speak" — never just "talking".
- For dance/movement: name the specific moves and rhythm: "{name} steps left foot
  forward, arms swing up in sync, hips rotate, then right foot crosses over".
- For action (fight, jump, run): describe the full arc of the motion with at least
  two beats: start position → peak → follow-through.
- For scenery or establishing shots: use slow camera drift or ambient movement:
  "slow upward tilt revealing the city skyline, gentle cloud drift, flags rippling".

Dialogue and voices:
- For narrator-style videos leave voice null everywhere (one narrator voice is used).
- If scenes are spoken BY different characters (dialogue), set voice per scene to a
  fitting edge-tts voice and write the narration as that character's spoken line.
  Examples: en-US-AndrewNeural / en-US-BrianNeural (male), en-US-JennyNeural /
  en-GB-SoniaNeural (female), ur-PK-UzmaNeural / ur-IN-GulNeural (Urdu female),
  ur-PK-AsadNeural (Urdu male), hi-IN-SwaraNeural (Hindi female).
- Match the voice language to the narration language.
"""


LITELLM_DEFAULT_MODEL = "groq/llama-3.3-70b-versatile"


def default_model() -> str:
    """Resolve the shot-plan model from the explicit LLM_PROVIDER flag (a friendly
    name, not a model id). No auto-detect: an unset/unknown provider, or a chosen
    provider whose key is missing, is an error."""
    provider = os.environ.get("LLM_PROVIDER", "").strip().lower()
    if not provider:
        raise RuntimeError(
            "no LLM provider set — put LLM_PROVIDER in .env "
            "(openai | litellm/libra | anthropic | gemini) or pass --model")
    if provider == "openai":
        model, need = "gpt-4o-mini", "OPENAI_API_KEY"
    elif provider in ("anthropic", "claude"):
        model, need = "claude-haiku-4-5", "ANTHROPIC_API_KEY"
    elif provider in ("gemini", "google"):
        model, need = "gemini-3.1-flash-lite", "GOOGLE_API_KEY"
    elif provider in ("litellm", "libra", "company"):
        model, need = os.environ.get("LITELLM_MODEL", LITELLM_DEFAULT_MODEL), "LITELLM_API_KEY"
    else:
        raise RuntimeError(
            f"unknown LLM_PROVIDER '{provider}' — use openai, litellm/libra, anthropic, or gemini")
    if not os.environ.get(need):
        raise RuntimeError(f"LLM provider '{provider}' is not configured — set {need} in .env")
    return model


_PROVIDER_SDK = {
    "openai":    ("openai",    "OPENAI_API_KEY",    None),
    "anthropic": ("anthropic", "ANTHROPIC_API_KEY",  None),
    "google":    ("openai",    "GOOGLE_API_KEY",     "https://generativelanguage.googleapis.com/v1beta/openai/"),
    "litellm":   ("openai",    "LITELLM_API_KEY",   None),
    "dashscope": ("openai",    "DASHSCOPE_API_KEY",  None),
}


def _infer_provider(model: str) -> str:
    if model.startswith("gpt"):
        return "openai"
    if model.startswith("claude"):
        return "anthropic"
    if model.startswith("gemini"):
        return "google"
    if model.startswith("qwen"):
        return "dashscope"
    return "litellm"


def _build_client(model: str, provider: str | None = None, api_key: SecureString | None = None):
    resolved_key = api_key.decrypt() if api_key else None
    resolved_provider = provider or _infer_provider(model)
    try:
        sdk_type, env_var, base_url = _PROVIDER_SDK[resolved_provider]
    except KeyError:
        raise ValueError(
            f"Provider {resolved_provider!r} is not supported for plan generation. "
            f"Supported providers: {', '.join(sorted(_PROVIDER_SDK))}"
        )

    if sdk_type == "anthropic":
        import anthropic
        return anthropic.Anthropic(api_key=resolved_key or os.environ.get(env_var))

    from openai import OpenAI
    if resolved_provider == "litellm":
        base_url = base_url or (os.environ.get("LITELLM_BASE_URL") or "https://litellm.arbisoft.com").rstrip("/")
    elif resolved_provider == "dashscope":
        from pipeline.env import dashscope_base_url
        base_url = dashscope_base_url() + "/compatible-mode/v1"
    return OpenAI(
        api_key=resolved_key or os.environ.get(env_var),
        base_url=base_url,
    )


def _parse_with_llm(user_content: str, model: str, system_extra: str | None = None,
                    provider: str | None = None, api_key: SecureString | None = None) -> ShotPlan:
    system = SYSTEM if not system_extra else f"{SYSTEM}\n\n{system_extra}"
    resolved_provider = provider or _infer_provider(model)
    client = _build_client(model, provider=resolved_provider, api_key=api_key)

    if resolved_provider == "anthropic":
        response = client.messages.parse(
            model=model,
            max_tokens=8192,
            system=system,
            messages=[{"role": "user", "content": user_content}],
            output_format=ShotPlan,
        )
        return response.parsed_output

    if resolved_provider == "openai":
        completion = client.chat.completions.parse(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_content},
            ],
            response_format=ShotPlan,
        )
        return completion.choices[0].message.parsed

    return _parse_json_mode(client, model, user_content, system=system)


# JSON schema embedded in the prompt for proxy models. Groq/Cerebras enforce
# json_schema via a flaky tool-call wrapper (it intermittently nests the whole
# plan in a {"json_string": "..."} envelope that fails validation), so we use
# plain JSON mode, hand the model the schema, and validate with Pydantic.
_SCHEMA_HINT = (
    "Respond with ONLY a single JSON object — no markdown, no code fences, no "
    "function wrapper, no commentary. It must match this exact JSON schema:\n\n"
    + json.dumps(ShotPlan.model_json_schema())
)


def _parse_json_mode(client, model: str, user_content: str, tries: int = 3,
                     system: str = SYSTEM) -> ShotPlan:
    messages = [
        {"role": "system", "content": system + "\n\n" + _SCHEMA_HINT},
        {"role": "user", "content": user_content},
    ]
    last_err = None
    for _ in range(tries):
        completion = client.chat.completions.create(
            model=model,
            messages=messages,
            response_format={"type": "json_object"},
        )
        raw = completion.choices[0].message.content or ""
        try:
            data = json.loads(raw)
            # safety net: some proxies still hand back the tool-call envelope
            if isinstance(data, dict) and list(data) == ["json_string"]:
                data = json.loads(data["json_string"])
            return ShotPlan.model_validate(data)
        except (json.JSONDecodeError, ValidationError) as e:
            last_err = e
            messages.append({"role": "assistant", "content": raw})
            messages.append({"role": "user", "content": (
                f"That response was invalid ({e}). Return ONLY the corrected "
                "JSON object matching the schema — nothing else.")})
    raise RuntimeError(
        f"model '{model}' did not return a valid shot plan after {tries} tries: {last_err}")


def generate_shot_plan(
    topic: str,
    model: str = "claude-haiku-4-5",
    style: dict | None = None,
    animate: bool = False,
    provider: str | None = None,
    api_key: SecureString | None = None,
) -> ShotPlan:
    from .styles import inject_style_instruction
    extras = []
    if style:
        extras.append(inject_style_instruction(style))
    if not animate:
        extras.append(
            "ANIMATION DISABLED: The user has not requested animation. "
            "Set animate=false on ALL scenes — do not animate any scene regardless of content."
        )
    system_extra = "\n\n".join(extras) if extras else None
    return _parse_with_llm(f"Topic / rough script:\n\n{topic}", model,
                           system_extra=system_extra, provider=provider, api_key=api_key)


def polish_image_prompts(
    plan: ShotPlan,
    model: str = "claude-haiku-4-5",
    provider: str | None = None,
    api_key: SecureString | None = None,
) -> ShotPlan:
    return _parse_with_llm(
        "Here is an existing shot plan JSON:\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Rewrite ONLY each scene's media_prompt field as an expert image-generation prompt, "
        "under ~60 words: add a shot type and camera angle, lighting, and a color/mood "
        "note, keeping the scene's subject and action unchanged. "
        "CRITICAL: Keep every {name} character placeholder EXACTLY as written — "
        "never expand them into descriptions, never reword, never remove them. "
        "The placeholder names MUST appear verbatim (e.g. {alice}, {bob}) so the "
        "pipeline can inject the correct character description at generation time. "
        "Return the COMPLETE plan with every other field (narration, voice, motion, "
        "characters, title, tags, ...) unchanged.",
        model, provider=provider, api_key=api_key,
    )


def consistency_review(
    plan: ShotPlan,
    model: str = "claude-haiku-4-5",
    animate: bool = True,
    provider: str | None = None,
    api_key: SecureString | None = None,
) -> ShotPlan:
    """Second-pass review focused entirely on character consistency errors."""
    return _parse_with_llm(
        "Review this shot plan for character consistency problems and return a corrected version.\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Check and fix ALL of the following — do not skip any:\n\n"
        "1. MISSING CHARACTERS: Scan every image_prompt. If any person, flag, building, "
        "or recurring object appears in more than one scene without a {placeholder}, "
        "add it to the characters list and replace every inline description with its placeholder.\n\n"
        "2. INLINE DESCRIPTIONS: If any image_prompt contains a character's physical description "
        "written out in full instead of using {placeholder}, replace it with the placeholder.\n\n"
        "3. CHARACTER NEGATIVES: Check each character's negative field:\n"
        "   - If negative is null, missing, empty, or the literal string 'none' — it MUST be fixed.\n"
        "   - Bald/no-hair character → must include: 'hair, any hair on head, hairline, wig'\n"
        "   - White-haired character → must include: 'dark hair, black hair, brown hair'\n"
        "   - Clean-shaven character → must include: 'beard, mustache, stubble'\n"
        "   - National flag → must include: 'wrong colors, altered design, incorrect emblem'\n"
        "   - Inanimate prop (food, landmark, vehicle, treasure — does NOT speak or "
        "show emotion in the story) → must set is_inanimate=true AND negative must include: "
        "'face, eyes, mouth, anthropomorphic, cartoon face, human features'\n"
        "   - Anthropomorphic object (talks, shows emotion, acts like a character in the "
        "story) → is_inanimate=false, treat like a person/animal, do NOT add anti-face "
        "negatives. Include facial features in the description instead.\n"
        "   - All other characters (people/animals) → is_inanimate=false, set negative to: "
        "'beard, mustache, different person'\n"
        "   Never leave negative as null or 'none'.\n\n"
        "4. VAGUE OBJECT DESCRIPTIONS: If any non-person character (food, prop, treasure) "
        "uses a generic term (e.g. 'red berry', 'a fruit', 'a gem'), rewrite the description "
        "to name the exact type with shape, texture, and distinguishing features "
        "(e.g. 'a giant bright red strawberry with visible seeds, a green leafy top, "
        "and a teardrop shape').\n\n"
        "5. SIZE COMPARISONS: If any character description uses a size comparison to another "
        "character or animal (e.g. 'the size of a small bird', 'as big as a cat'), rewrite it "
        "using absolute terms only (e.g. 'oversized', 'palm-sized', 'enormous'). The image "
        "model will draw the compared thing.\n\n"
        + (
            "6. ANIMATE CAP: At most 2 scenes may have animate=true. If more than 2 are set, "
            "set the least important ones back to false.\n\n"
            if animate else
            "6. ANIMATION DISABLED: The user has NOT enabled animation for this project. "
            "Every scene MUST have animate=false. If any scene has animate=true, set it to false.\n\n"
        ) +
        "7. OUTFIT CONSISTENCY: If a character has outfits defined, verify that every "
        "outfit value repeats the full identity (face, hair, build, skin) from the "
        "character's description — only clothing should differ. Also verify that every "
        "scene after a clothing change sets the outfit field correctly.\n\n"
        "Return the COMPLETE corrected plan with ALL fields intact. "
        "Only change what the checks above require.",
        model, provider=provider, api_key=api_key,
    )


def refine_plan(
    plan: ShotPlan,
    *,
    model: str = "claude-haiku-4-5",
    animate: bool = False,
    polish: bool = True,
    review: bool = True,
    on_write=None,
) -> ShotPlan:
    """Standard post-generation refinement: polish image prompts, then run the
    consistency review — the sequence shared by pipeline.run and pipeline.refine.

    ``animate`` is threaded into consistency_review so the review picks the same
    animate-cap vs animation-disabled clause the generator used. ``on_write(plan)``
    is called after each pass so callers can persist the intermediate plan.
    """
    if polish:
        print(f"  polishing image prompts ({model})...")
        plan = polish_image_prompts(plan, model=model)
        if on_write:
            on_write(plan)
    if review:
        print(f"  consistency review ({model})...")
        plan = consistency_review(plan, model=model, animate=animate)
        if on_write:
            on_write(plan)
    return plan


def revise_shot_plan(
    plan: ShotPlan,
    feedback: str,
    model: str = "claude-haiku-4-5",
    provider: str | None = None,
    api_key: SecureString | None = None,
) -> ShotPlan:
    return _parse_with_llm(
        "Here is an existing shot plan JSON:\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Apply the following feedback and return the COMPLETE updated shot plan. "
        "Change only what the feedback requires and keep everything else identical. "
        "If the feedback changes a character's look, update that character's "
        "description verbatim in every scene where they appear:\n\n"
        f"{feedback}",
        model, provider=provider, api_key=api_key,
    )
