"""Stage 1: topic -> refined script -> shot plan JSON (one LLM call).

Provider is picked by the model name: "claude-*" uses Anthropic (ANTHROPIC_API_KEY),
"gpt-*" uses OpenAI (OPENAI_API_KEY).
"""
import os

from .schema import ShotPlan

SYSTEM = """You are a scriptwriter for a faceless YouTube channel. Given a topic or rough
script, produce a complete shot plan for a 60-90 second video built from still images,
voiceover, and captions.

Rules:
- The first scene's narration must hook the viewer in one sentence — open with a question,
  a surprising fact, or a bold claim. Never open with "Welcome" or "In this video".
- Keep narration conversational and punchy. Short sentences. No filler.
- Each scene's narration should take roughly 4-8 seconds to speak aloud.
- For educational / listicle topic videos only: end with a one-sentence call to action
  (subscribe / comment prompt). For stories, dialogues, and personal videos, do NOT add
  any call-to-action or subscribe scene — end on the story's natural final beat.
- image_prompt must describe a concrete visual, never abstract concepts. Do not ask for
  rendered text in images — text belongs in on_screen_text.
- Write each image_prompt like a cinematographer, in under ~60 words: include a shot type
  and angle (wide establishing shot, close-up, low-angle medium shot, over-the-shoulder),
  lighting (golden hour, harsh neon, soft window light, police lights raking the wall),
  and a color/mood note. Example: "low-angle medium shot, {thief} pressed against the
  lockers, red-blue police light raking across his face, shallow depth of field, tense".
- Never put negations in image_prompt ("no beard" makes models DRAW a beard) — unwanted
  traits go in the scene's negative_prompt field.
- Pick one consistent style_prefix and write every image_prompt to work with it.

CHARACTER AND VISUAL CONSISTENCY — the most important rule:

Each scene's image is generated by an AI that has NEVER seen the other scenes.
Writing "Argentina flag" in scene 3 and "Argentina flag" in scene 7 produces TWO
DIFFERENT flags from scratch. This is why people, flags, and buildings look different
every scene unless you lock them.

THE RULE: Any visual element appearing in more than one scene MUST be a character entry.
This includes: people, animals, national flags, team kits/uniforms, specific buildings,
vehicles, logos, any recurring object.

WRONG (produces a different flag every scene):
  scene 3 image_prompt: "Argentina flag waving in the wind"
  scene 7 image_prompt: "the Argentine flag above the crowd"

RIGHT (locked once, identical in every scene):
  characters: [{"name": "arg_flag", "description": "the Argentina national flag —
    three equal horizontal stripes of light sky-blue, white, and light sky-blue,
    with a bright golden Sun of May centered on the white stripe"}]
  scene 3 image_prompt: "{arg_flag} waving dramatically in the wind, low-angle shot"
  scene 7 image_prompt: "{arg_flag} flying above the roaring crowd, wide shot"

DESCRIPTION RULES:
- Description = visual identity only: colors, shape, materials, markings, clothing.
  NEVER include pose, action, emotion — those go in image_prompt.
- Be specific. WEAK: "an Argentina flag". STRONG: see example above.
- Always use {placeholder} — never write the description inline, never use
  "he"/"she"/"the flag"/"the man". Always {placeholder}.
- For national flags: always include stripe direction, exact colors, and central emblem.
- For people: age range, hair color/style, skin tone, every clothing item with color.

CHARACTER NEGATIVE (negative field on each character — critical for unusual traits):
- Set the character's negative field for any trait the image model tends to add wrongly.
- Bald character → negative: "hair, any hair on head, wig, hairline"
- White-haired character → negative: "dark hair, black hair, brown hair, colored hair"
- Clean-shaven character → negative: "beard, mustache, stubble, facial hair"
- This negative is automatically injected into EVERY scene the character appears in,
  so you never have to remember to add it per scene.

GLOBAL NEGATIVE: Always set global_negative on the plan with video-wide rules:
- Videos with people: "changing hairstyle, inconsistent clothing, different face, extra limbs, text, watermark, blurry"
- Add for flags: "wrong flag colors, altered flag design, swapped flags"
- Add for animals: "wrong species, inconsistent markings"
This is merged into EVERY scene automatically — do not repeat it per scene.

FINAL CHECK before outputting: scan every image_prompt. If any person, flag, building,
or object appears in more than one scene and is NOT referenced as {placeholder} — stop
and add it to characters. No exceptions.

Animation cost (animate field — hard limit: maximum 2 scenes per video):
- Set animate=true ONLY for the 1-2 scenes where motion is absolutely essential:
  flags waving, a character fighting/dancing/running, an animal attacking, crowd surging.
- Set animate=false for everything else: title cards, portraits, establishing shots,
  object reveals. Ken Burns zoom handles these for free.
- The pipeline enforces a hard cap of 2 — extra animate=true entries are ignored.

Motion (each still may be animated into a video clip):
- Write the motion field as a precise, physical action description — name the body
  parts, direction, and speed. Bad: "the lion attacks". Good: "the lion crouches low,
  then springs forward with front paws outstretched, mouth opening wide".
- For a speaking character: "{name} is talking, jaw moving, eyes blinking naturally,
  slight head nods as they speak" — never just "talking".
- For dance/movement: name the specific moves and rhythm: "{name} steps left foot
  forward, arms swing up in sync, hips rotate, then right foot crosses over".
- For action (fight, jump, run): describe the full arc of the motion with at least
  two beats: start position → peak → follow-through.
- For scenery or establishing shots: use slow camera drift or ambient movement:
  "slow upward tilt revealing the city skyline, gentle cloud drift, flags rippling".

Dialogue and voices:
- For narrator-style videos leave voice null everywhere (one narrator voice is used).
- If scenes are spoken BY different characters (dialogue), set voice per scene to a
  fitting edge-tts voice and write the narration as that character's spoken line.
  Examples: en-US-AndrewNeural / en-US-BrianNeural (male), en-US-JennyNeural /
  en-GB-SoniaNeural (female), ur-PK-UzmaNeural / ur-IN-GulNeural (Urdu female),
  ur-PK-AsadNeural (Urdu male), hi-IN-SwaraNeural (Hindi female).
- Match the voice language to the narration language.
"""


def default_model() -> str:
    return "claude-haiku-4-5" if os.environ.get("ANTHROPIC_API_KEY") else "gpt-4o-mini"


def _parse_with_llm(user_content: str, model: str) -> ShotPlan:
    if model.startswith("gpt"):
        from openai import OpenAI

        client = OpenAI()  # reads OPENAI_API_KEY from env
        completion = client.chat.completions.parse(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": user_content},
            ],
            response_format=ShotPlan,
        )
        return completion.choices[0].message.parsed

    import anthropic

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env
    response = client.messages.parse(
        model=model,
        max_tokens=8192,
        system=SYSTEM,
        messages=[{"role": "user", "content": user_content}],
        output_format=ShotPlan,
    )
    return response.parsed_output


def generate_shot_plan(topic: str, model: str = "claude-haiku-4-5") -> ShotPlan:
    return _parse_with_llm(f"Topic / rough script:\n\n{topic}", model)


def polish_image_prompts(plan: ShotPlan, model: str = "claude-haiku-4-5") -> ShotPlan:
    return _parse_with_llm(
        "Here is an existing shot plan JSON:\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Rewrite ONLY each scene's image_prompt as an expert image-generation prompt, "
        "under ~60 words: add a shot type and camera angle, lighting, and a color/mood "
        "note, keeping the scene's subject and action unchanged. Keep {name} character "
        "placeholders EXACTLY as written — never expand, reword, or remove them. Return "
        "the COMPLETE plan with every other field (narration, voice, motion, characters, "
        "title, tags, ...) unchanged.",
        model,
    )


def consistency_review(plan: ShotPlan, model: str = "claude-haiku-4-5") -> ShotPlan:
    """Second-pass review focused entirely on character consistency errors."""
    return _parse_with_llm(
        "Review this shot plan for character consistency problems and return a corrected version.\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Check and fix ALL of the following — do not skip any:\n\n"
        "1. MISSING CHARACTERS: Scan every image_prompt. If any person, flag, building, "
        "or recurring object appears in more than one scene without a {placeholder}, "
        "add it to the characters list and replace every inline description with its placeholder.\n\n"
        "2. INLINE DESCRIPTIONS: If any image_prompt contains a character's physical description "
        "written out in full instead of using {placeholder}, replace it with the placeholder.\n\n"
        "3. CHARACTER NEGATIVES: Check each character's negative field:\n"
        "   - If negative is null, missing, empty, or the literal string 'none' — it MUST be fixed.\n"
        "   - Bald/no-hair character → must include: 'hair, any hair on head, hairline, wig'\n"
        "   - White-haired character → must include: 'dark hair, black hair, brown hair'\n"
        "   - Clean-shaven character → must include: 'beard, mustache, stubble'\n"
        "   - National flag → must include: 'wrong colors, altered design, incorrect emblem'\n"
        "   - All other characters → set negative to: 'beard, mustache, different person'\n"
        "   Never leave negative as null or 'none'.\n\n"
        "4. ANIMATE CAP: At most 2 scenes may have animate=true. If more than 2 are set, "
        "set the least important ones back to false.\n\n"
        "Return the COMPLETE corrected plan with ALL fields intact. "
        "Only change what the checks above require.",
        model,
    )


def revise_shot_plan(plan: ShotPlan, feedback: str, model: str = "claude-haiku-4-5") -> ShotPlan:
    return _parse_with_llm(
        "Here is an existing shot plan JSON:\n\n"
        f"{plan.model_dump_json(indent=2)}\n\n"
        "Apply the following feedback and return the COMPLETE updated shot plan. "
        "Change only what the feedback requires and keep everything else identical. "
        "If the feedback changes a character's look, update that character's "
        "description verbatim in every scene where they appear:\n\n"
        f"{feedback}",
        model,
    )
