# Generated by Django 5.2.15 on 2026-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_user_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapikey",
            name="api_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
